export const LoginActionTypes = {
    LOGGED_STATUS: 'LOGGED_STATUS',
    LOGIN_START: 'LOGIN_START',
    LOGIN_EMAIL: 'LOGIN_EMAIL',
    LOGIN_PASSWORD: 'LOGIN_PASSWORD',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    ACCESS_TOKEN: 'ACCESS_TOKEN',
    EXPIRES_IN: 'EXPIRES_IN',
    USER_DATA: 'USER_DATA',
};

export const OrderActionTypes = {
    SET_SECTION: 'SET_SECTION',
    // Compras
    SET_SELECTED_COMPRAS: 'SET_SELECTED_COMPRAS',
    GET_COMPRAS: 'GET_COMPRAS',
    SET_COMPRAS: 'SET_COMPRAS',
    GET_MY_COMPRAS: 'GET_MY_COMPRAS',
    SET_MY_COMPRAS: 'SET_MY_COMPRAS',
    // Observaciones
    SET_OBSERVACIONES: 'SET_OBSERVACIONES',
    CLEAR_NEW_ORDER: 'CLEAR_NEW_ORDER',
    // Pedido
    PEDIDO_SUCCESS: 'PEDIDO_SUCCESS',
    PEDIDO_FAILURE: 'PEDIDO_FAILURE',
    GET_PEDIDOS_TODOS: 'GET_PEDIDOS_TODOS',
    GET_PEDIDOS_USER: 'GET_PEDIDOS_USER',
    GET_PEDIDOS_START: 'GET_PEDIDOS_START',
    GET_PEDIDOS_SUCCESS: 'GET_PEDIDOS_SUCCESS',
    GET_PEDIDOS_FAILED: 'GET_PEDIDOS_FAILED',
    SET_PEDIDO_SELECTED_TODOS: 'SET_PEDIDO_SELECTED_TODOS',
    SET_PEDIDO_SELECTED_BY_USER: 'SET_PEDIDO_SELECTED_BY_USER',
};
export const FirstSectionActionTypes = {
    // Remitentes
    GET_REMITENTES: 'GET_REMITENTES',
    GET_REMITENTES_START: 'GET_REMITENTES_START',
    GET_REMITENTES_SUCCESS: 'GET_REMITENTES_SUCCESS',
    GET_REMITENTES_FAILURE: 'GET_REMITENTES_FAILURE',
    SET_REMITENTES: 'SET_REMITENTES',
    SET_SEARCH_REMITENTES: 'SET_SEARCH_REMITENTES',
    SET_SELECTED_REMITENTES: 'SET_SELECTED_REMITENTES',
    // Provincias
    GET_PROVINCIAS: 'GET_PROVINCIAS',
    SET_PROVINCIAS: 'SET_PROVINCIAS',
    GET_PROVINCIAS_START: 'GET_PROVINCIAS_START',
    GET_PROVINCIAS_SUCCESS: 'GET_PROVINCIAS_SUCCESS',
    GET_PROVINCIAS_FAILURE: 'GET_PROVINCIAS_FAILURE',
    // Localidades
    GET_LOCALIDADES: 'GET_LOCALIDADES',
    SET_LOCALIDADES: 'SET_LOCALIDADES',
    GET_LOCALIDADES_START: 'GET_LOCALIDADES_START',
    GET_LOCALIDADES_SUCCESS: 'GET_LOCALIDADES_SUCCESS',
    GET_LOCALIDADES_FAILURE: 'GET_LOCALIDADES_FAILURE',
    SET_SEARCH_LOCALIDADES: 'SET_SEARCH_LOCALIDADES',
    // Plazos
    GET_PLAZOS: 'GET_PLAZOS',
    SET_SELECTED_PLAZO: 'SET_SELECTED_PLAZO',
    SET_OTHER_PLAZO: 'SET_OTHER_PLAZO',
    SET_OTHER_PLAZO_ID: 'SET_OTHER_PLAZO_ID',
    // CLEAR SECTION
    CLEAR_SECTION_1: 'CLEAR_SECTION_1',
};
export const SecondSectionActionTypes = {
    // Tipo Animal
    TIPO_COMPRA: 'TIPO_COMPRA',
    KG_VIVO: 'KG_VIVO',
    AL_RINDE: 'AL_RINDE',
    GET_ANIMALES: 'GET_ANIMALES',
    // KG VIVO
    SET_CANTIDAD_KG_VIVO: 'SET_CANTIDAD_KG_VIVO',
    SET_KG_KG_VIVO: 'SET_KG_KG_VIVO',
    SET_PRECIO_KG_VIVO: 'SET_PRECIO_KG_VIVO',
    ADD_NEW_KG_VIVO: 'ADD_NEW_KG_VIVO',
    SET_SELECTED_ANIMAL: 'SET_SELECTED_ANIMAL',
    TA_CANTIDAD: 'TA_CANTIDAD',
    TA_KG: 'TA_KG',
    TA_PRECIO: 'TA_PRECIO',
    CLEAR_NEW_KG_VIVO: 'CLEAR_NEW_KG_VIVO',
    // AL RINDE
    SET_SELECTED_ANIMAL_AR: 'SET_SELECTED_ANIMAL_AR',
    SET_CANTIDAD_AL_RINDE: 'SET_CANTIDAD_AL_RINDE',
    SET_PRECIO_PAC_AL_RINDE: 'SET_PRECIO_PAC_AL_RINDE',
    SET_SELECTED_ALRINDE_ITEM: 'SET_SELECTED_ALRINDE_ITEM',
    ADD_NEW_AL_RINDE: 'ADD_NEW_AL_RINDE',
    FINAL_LIST_AL_RINDE: 'FINAL_LIST_AL_RINDE',
    AL_RINDE_SEND: 'AL_RINDE_SEND',
    CLEAR_ALRINDE_LISTS: 'CLEAR_ALRINDE_LISTS',
    CLEAR_AL_RINDE: 'CLEAR_AL_RINDE',
    // CLEAR SECTION
    CLEAR_SECTION_2: 'CLEAR_SECTION_2',
};
export const ThirdSectionActionTypes = {
    // Comisionista
    GET_COMISIONISTA: 'GET_COMISIONISTA',
    SET_SEARCH_COMISIONISTA: 'SET_SEARCH_COMISIONISTA',
    SET_SELECTED_COMISIONISTA: 'SET_SELECTED_COMISIONISTA',
    COMISIONISTA_SWITCH: 'COMISIONISTA_SWITCH',
    // Destino
    GET_DESTINOS: 'GET_DESTINOS',
    SET_SEARCH_DESTINO: 'SET_SEARCH_DESTINO',
    SET_SELECTED_DESTINO: 'SET_SELECTED_DESTINO',
    // Destino Disponibilidad
    GET_DESTINO_DISPONIBILIDAD: 'GET_DESTINO_DISPONIBILIDAD',
    SET_DESTINO_ID: 'SET_DESTINO_ID',
    SET_SELECTED_FECHA: 'SET_SELECTED_FECHA',
    SHOW_FECHAS: 'SHOW_FECHAS',
    DESTINO_FECHAS: 'DESTINO_FECHAS',
    DESTINO_COLOR_DAY: 'DESTINO_COLOR_DAY',
    // CLEAR SECTION
    CLEAR_SECTION_3: 'CLEAR_SECTION_3',
};
export const FourthSectionActionTypes = {
    // Transporte
    GET_TRANSPORTES_START: 'GET_TRANSPORTES_START',
    GET_TRANSPORTES_SUCCESS: 'GET_TRANSPORTES_SUCCESS',
    GET_TRANSPORTES_FAILURE: 'GET_TRANSPORTES_FAILURE',
    GET_TRANSPORTE_JAULAS_START: 'GET_TRANSPORTE_JAULAS_START',
    GET_TRANSPORTE_JAULAS_SUCCESS: 'GET_TRANSPORTE_JAULAS_SUCCESS',
    GET_TRANSPORTE_JAULAS_FAILURE: 'GET_TRANSPORTE_JAULAS_FAILURE',
    SET_SELECTED_TRANSPORTE: 'SET_SELECTED_TRANSPORTE',
    SET_SELECTED_TRANSPORTE_ID: 'SET_SELECTED_TRANSPORTE_ID',
    SET_SEARCH_TRANSPORTE: 'SET_SEARCH_TRANSPORTE',
    GET_TRANSPORTES_TIPO_START: 'GET_TRANSPORTES_TIPO_START',
    GET_TRANSPORTES_TIPO_SUCCESS: 'GET_TRANSPORTES_TIPO_SUCCESS',
    GET_TRANSPORTES_TIPO_FAILURE: 'GET_TRANSPORTES_TIPO_FAILURE',
    SET_SELECTED_TRANSPORTE_TIPO: 'SET_SELECTED_TRANSPORTE_TIPO',
    SET_TRANSP_PKM: 'SET_TRANSP_PKM',
    SET_TRANSP_CANT_JAULAS: 'SET_TRANSP_CANT_JAULAS',
    ADD_NEW_TRANSPORTE: 'ADD_NEW_TRANSPORTE',
    CLEAR_NEW_TRANSPORTE: 'CLEAR_NEW_TRANSPORTE',
    // CLEAR SECTION
    CLEAR_SECTION_4: 'CLEAR_SECTION_4',
};
export const FifthSectionActionTypes = {
    // Observaciones
    SET_OBSERVACIONES: 'SET_OBSERVACIONES',
    CLEAR_NEW_ORDER: 'CLEAR_NEW_ORDER',
    // Pedido
    PEDIDO_SUCCESS: 'PEDIDO_SUCCESS',
    PEDIDO_STATUS_RESPONSE: 'PEDIDO_STATUS_RESPONSE',
    PEDIDO_STATUS_MESSAGE: 'PEDIDO_STATUS_MESSAGE',
    GET_PEDIDOS_TODOS: 'GET_PEDIDOS_TODOS',
    GET_PEDIDOS_USER: 'GET_PEDIDOS_USER',
    GET_PEDIDOS_START: 'GET_PEDIDOS_START',
    GET_PEDIDOS_SUCCESS: 'GET_PEDIDOS_SUCCESS',
    SET_PEDIDO_SELECTED_TODOS: 'SET_PEDIDO_SELECTED_TODOS',
    SET_PEDIDO_SELECTED_BY_USER: 'SET_PEDIDO_SELECTED_BY_USER',
    SHOW_MODAL_RESPONSE_ORDER: 'SHOW_MODAL_RESPONSE_ORDER',
    CLEAR_SECTION_5: 'CLEAR_SECTION_5',
};
export const HomeActionTypes = {
    GET_PCP_7DAYS: 'GET_PCP_7DAYS',
    GET_PCP_30DAYS: 'GET_PCP_30DAYS',
    GET_PFP_7DAYS: 'GET_PFP_7DAYS',
    GET_PFP_30DAYS: 'GET_PFP_30DAYS',
};
